# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4afdaa930ae39bbbce5983950cb582cc"
application_url = "https://union-worry-tasks-prev.trycloudflare.com"
embedded = true
name = "announcemen1"
handle = "announcemen1"

[build]
include_config_on_deploy = true
dev_store_url = "mannounce.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://union-worry-tasks-prev.trycloudflare.com/auth/callback",
  "https://union-worry-tasks-prev.trycloudflare.com/auth/shopify/callback",
  "https://union-worry-tasks-prev.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
